# Copyright 2018, Juniper Networks Pvt Ltd.
# All rights reserved.
# command example: ansible-playbook -i all.inv 02-deploy-networks.yml
---
- name: install contrail
  hosts: contrail-ubuntu-vm
  gather_facts: false
  vars:
    openrc:
      OS_PROJECT_DOMAIN_NAME: default
      OS_USER_DOMAIN_NAME: default
      OS_PROJECT_NAME: admin
      OS_TENANT_NAME: admin
      OS_USERNAME: admin
      OS_PASSWORD: contrail123
      OS_AUTH_URL: http://10.10.7.205:35357/v3
      OS_INTERFACE: internal
      OS_IDENTITY_API_VERSION: 3

  environment: "{{ openrc }}"
  tasks:

    - name: Gather facts about previously created subnets
      shell: openstack --os-auth-url "http://10.10.7.205:35357/v3" --os-username admin --os-project-name admin --os-tenant-name admin --os-password "contrail123" --os-default-domain-name default subnet list -f json
      register: network_list

    - name: Display Networks
      set_fact:
        subnets: "{{ network_list.stdout | from_json | json_query(jq)}}"
      vars:
        jq: "[?contains(Name,'')].{ID:ID,Network:Network,Subnet:Subnet}"
    - debug:
        msg:
          - "{{subnets}}"
