# Copyright 2018, Juniper Networks Pvt Ltd.
# All rights reserved.
---
- name: Collect facts from the contrail host machine
  hosts: "{{ target }}"
  gather_facts: no
  tasks:
  - name: Install 
  - name: Get the cidr of the network
