# Copyright 2018, Juniper Networks Pvt Ltd.
# All rights reserved.
---
- name: Collect facts from the contrail host machine
  hosts: ubuntu-contrail-vm
  gather_facts: no
  tasks:
  - name: Install sipcalc
    apt:
      name: sipcalc
      
  - name: Get the cidr of the network
    shell: |
      sipcalc "{{ iface }}" | grep 'Network mask (bits)'| awk 'NR==1'|awk -F ' ' '{print $5}'
    register: cidr
    args:
      executable: /bin/bash
    
  - name: Write to file contrail-host-data.txt
    local_action: lineinfile path="/root/Contrail_Automation/contrail-host-data.txt" line=cidr "{{ cidr.stdout_lines }}"
    
  - debug:
      msg: cidr.stdout_lines
    
  - name: Get the hostname of the target
    shell: |
      hostname
    register: hostname
    args:
      executable: /bin/bash
    
  - debug:
      msg: hostname.stdout_lines
      
  - name: Get the mac of the network interface
    shell: |
      /sbin/ifconfig "{{ iface }}" $1 | grep "HWaddr" | awk -F ' ' '{print $5}'
    register: mac
    args:
      executable: /bin/bash
    
  - debug:
      msg: mac.stdout_lines
      
  - name: Get the gateway of the network interface
    shell: |
      ip route list dev "{{ iface }}" | awk ' /^default/ {print $3}'
    register: gw
    args:
      executable: /bin/bash
    
  - debug:
      msg: gw.stdout_lines
