# Copyright 2018, Juniper Networks Pvt Ltd.
# All rights reserved.
---
- name: Collect facts from the contrail host machine
  hosts: "{{ target }}"
  gather_facts: no
  tasks:
  - name: Install sipcalc
    apt:
      name: sipcalc
      
  - name: Get the cidr of the network
    shell: |
      sipcalc "{{ iface }}" | grep 'Network mask (bits)'| awk 'NR==1'|awk -F' ' '{print $5}'
    register: cidr
    args:
      executable: /bin/bash
    
  - debug:
      msg: cidr.stdout-lines
    
